### ISSUE TITLE
[Error: Couldn't find a suitable audio player]

### ISSUE THREAD

**Issue by prithviraj99** [shime/play-sound#10] opened 2016-04-14 14:26 UTC
I have installed mplayer for windows but still its giving this error.
[Error: Couldn't find a suitable audio player]

**Comment by shime** [comment] 2016-04-15 11:35
What happens if you specify a player manually?

```
var player = require('play-sound')({player: "mplayer"})
player.play('foo.mp3', function(err){})
```

**Comment by prithviraj99** [comment] 2016-04-15 20:09
{ [Error: spawn mplayer ENOENT]
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn mplayer',
  path: 'mplayer',
  spawnargs: [ './Ipl Trumpet Mix-(FreshMaza.co).mp3' ],
  cmd: 'mplayer ./Ipl Trumpet Mix-(FreshMaza.co).mp3' }

This is the error i'm getting.

**Comment by verth** [comment] 2016-07-27 20:23
@prithviraj99 

Perhaps a stupid question, but did you install mplayer so it was available through the command line. 

`cmd` > `mplayer` should not result in `'mplayer' is not recognized as an internal or external command`. I can reproduce your error by specifying a player that is not available as a command and thus can't be spawned (ENOENT).

A quick Google gave me as first results mplayer binary executables for Windows, which can be used with `play-sound` though (and are easy portable), as:

```javascript
var player = require('play-sound')({player: "/path/to/downloads/mplayer/mplayer.exe"})
player.play('foo.mp3', function(err){})
```

(cc @shime)

**Comment by shime** [comment] 2016-10-23 08:29
Thanks @verth, closing due to inactivity.

**Comment by avalanche1** [comment] 2017-02-01 15:49
I'm having the same problem. I've followed all of @verth's advice and and get the same ENOENT error @prithviraj99 was having.

**Comment by avalanche1** [comment] 2017-02-02 11:23
Ok, I've found the root cause:
I'm using this on windows and if I have file paths somewhere in the code - it gives ENOENT error.
`C:\Windows\Media\chimes.wav`
must be
`C:\\Windows\\Media\\chimes.wav`

**Comment by shime** [comment] 2017-02-02 12:27
@avalanche1 glad you found the solution, closing this again.

**Closed by shime** 2017-02-02 12:27 UTC

**Comment by harishvarma8055** [comment] 2017-04-27 18:08
How can we stop the audio..It keeps on playing on my node js file.audio.kill() is not working.It says it is not a function

**Comment by justinjmoses** [comment] 2017-04-27 19:36
Did you see the last example in the README? https://github.com/shime/play-sound#examples
